version: '3.8'

services:
  app:
    build: .
    container_name: xcelify-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/xcelify
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mynetwork

  db:
    image: mysql:8
    container_name: xcelify-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xcelify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge